# Spring Application Configuration
spring.application.name=tailor-backend
server.port=8080

# Spring Data MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/tailoring_db

# Static Resource & Server Logging
logging.level.com.tailor=INFO
logging.level.org.springframework.data.mongodb=INFO
